// USER TYPES
export const REGISTER_USER = "REGISTER_USER";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const AUTH_ERROR = "AUTH_ERROR";

// TOPIC TYPES
export const FETCH_TOPICS_SUCCESS = "FETCH_TOPICS_SUCCESS";
export const FETCH_TOPICS_FAILED = "FETCH_TOPICS_FAILED";

export const ADDING_TOPIC = "ADDING_TOPIC";
export const ADD_TOPIC_SUCCESS = "ADD_TOPIC_SUCCESS";
export const ADD_TOPIC_FAILED = "ADD_TOPIC_FAILED";

export const FETCH_TOPIC_SUCCESS = "FETCH_TOPIC_SUCCESS";
export const FETCH_TOPIC_FAILED = "FETCH_TOPIC_FAILED";

export const REMOVING_TOPIC = "REMOVING_TOPIC";
export const REMOVE_TOPIC_SUCCESS = "REMOVE_TOPIC_SUCCESS";
export const REMOVE_TOPIC_FAILED = "REMOVE_TOPIC_FAILED";


// ARGUMENT TYPES
export const FETCHING_ARGUMENTS = "FETCHING_ARGUMENTS";
export const FETCH_ARGUMENTS_SUCCESS = "FETCH_ARGUMENTS_SUCCESS";
export const FETCH_ARGUMENTS_FAILED = "FETCH_ARGUMENTS_FAILED";

export const ADDING_ARGUMENT = "ADDING_ARGUMENT";
export const ADD_ARGUMENT_SUCCESS = "ADD_ARGUMENT_SUCCESS";
export const ADD_ARGUMENT_FAILED = "ADD_ARGUMENT_FAILED";

export const REMOVING_ARGUMENT = "REMOVING_ARGUMENT";
export const REMOVE_ARGUMENT_SUCCESS = "REMOVE_ARGUMENT_SUCCESS";
export const REMOVE_ARGUMENT_FAILED = "REMOVE_ARGUMENT_FAILED";